config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :home, only: %i[show]
  resources :tabs, only: :show, param: :name

  # Defines the root path route ("/")
  root "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  def show
    render locals: { name: params[:name] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<h1>Hello world</h1>

<nav>
  <ul>
    <% %w[one two three].each do |name| %>
      <li><%= link_to "Tab #{name}", tab_path(name), data: { turbo_frame: "tabs" } %>
    <% end %>
  </ul>
</nav>

<%= turbo_frame_tag "tabs", src: tab_path("one"), data: {turbo_action: "advance"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrameTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tabs/show.html.erb
<%= turbo_frame_tag "tabs" do %>
  Tab <%= name %> content
<% end %>